[build]
  command = "npm run production"
  publish = "public"

[[headers]]
  for = "*.avif"
  [headers.values]
    Content-Type = "image/avif"
    Content-Disposition = "inline"

[[headers]]
  for = "/fonts/*"
    [headers.values]
    Cache-Control = "public, max-age=15768000"

[[headers]]
  for = "/img/*"
    [headers.values]
    Cache-Control = "public, max-age=604800"

[[redirects]]
  from = "/notes/shifthing-things-around/"
  to = "/notes/shifting-things-around/"
