[build]
  command = "npm run production"
  publish = "public"

[build.environment]
  NODE_VERSION = "lts/*"

[[headers]]
  for = "*.avif"
  [headers.values]
    Content-Type = "image/avif"
    Content-Disposition = "inline"

[[headers]]
  for = "/fonts/*"
    [headers.values]
    Cache-Control = "public, max-age=15768000"

[[redirects]]
  from = "/notes/shifthing-things-around/"
  to = "/notes/shifting-things-around/"
