[build]
  command = "npm run production"
  publish = "public"

[[headers]]
  for = "*.avif"
  [headers.values]
    Content-Type = "image/avif"
    Content-Disposition = "inline"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"

[[headers]]
  for = "/fonts/*"
    [headers.values]
    Cache-Control = "public, max-age=2592000"
